// Text for the operations modules (phases 2-14), English and Arabic.
// Merged into i18n.js; kept apart so each file stays readable.

export const en = {
  // navigation and pages
  analytics: 'Analytics', finance: 'Finance', schedule: 'Schedule', mySchedule: 'My schedule', approvals: 'Approvals',
  myRequests: 'My requests', attendance: 'Attendance', myPay: 'My pay', myExpenses: 'My expenses', payroll: 'Payroll',
  reports: 'Reports', settings: 'Settings', notifications: 'Notifications', search: 'Search', searchEverything: 'Search people, shifts, expenses, reports…',
  noResults: 'Nothing found.', overview: 'Overview', pay: 'Pay', shifts: 'Shifts', documents: 'Documents', profile: 'Profile',
  // generic
  add: 'Add', edit: 'Edit', delete: 'Delete', remove: 'Remove', open: 'Open', archive: 'Archive', archived: 'Archived', details: 'Details',
  history: 'History', reason: 'Reason', note: 'Note', notes: 'Notes', name: 'Name', type: 'Type', date: 'Date', amount: 'Amount', total: 'Total',
  status: 'Status', period: 'Period', month: 'Month', person: 'Person', description: 'Description', category: 'Category', share: 'Share',
  current: 'Current', today: 'Today', thisWeek: 'This week', upcoming: 'Upcoming', previous: 'Previous', other: 'Other', everyone: 'Everyone',
  seeAll: 'See all', review: 'Review', dismiss: 'Dismiss', accept: 'Accept', decline: 'Decline', approve: 'Approve', reject: 'Reject',
  noData: 'No data for this period.', hoursShort: 'h', hoursCol: 'Hours', points: 'pts', vsPrevious: 'compared with the previous period',
  showTable: 'Table', showChart: 'Chart', chartHint: 'Use the arrow keys to move through the values.', dateRange: 'Date range',
  attachFile: 'Attach photo or PDF', uploading: 'Uploading…', uploaded: 'Uploaded', icon: 'Icon', address: 'Address', location: 'Location',
  vendor: 'Vendor', customerSource: 'Customer / source', paymentMethod: 'Payment method', receipt: 'Receipt', receiptDocument: 'Receipt or document',
  timezone: 'Time zone', currency: 'Currency', decimals: 'decimal places', departments: 'Departments', locations: 'Locations',
  // date ranges
  range_today: 'Today', range_yesterday: 'Yesterday', range_thisWeek: 'This week', range_lastWeek: 'Last week', range_thisMonth: 'This month',
  range_lastMonth: 'Last month', range_thisQuarter: 'This quarter', range_thisYear: 'This year', range_lastYear: 'Last year', range_custom: 'Custom range',
  // statuses
  st_pending: 'Pending', st_submitted: 'Submitted', st_under_review: 'Under review', st_pending_peer: 'Waiting for colleague',
  st_pending_approval: 'Waiting for approval', st_review: 'Requires review', st_draft: 'Draft', st_approved: 'Approved', st_completed: 'Completed',
  st_paid: 'Paid', st_reimbursed: 'Reimbursed', st_finalized: 'Finalized', st_scheduled: 'Scheduled', st_working: 'Working', st_done: 'Finished',
  st_rejected: 'Rejected', st_cancelled: 'Cancelled', st_missed: 'Missed', st_late: 'Late', st_open: 'Open', st_upcoming: 'Upcoming', st_rescheduled: 'Rescheduled',
  // home
  howIsBusiness: 'How is my business doing?', monthToDate: 'This month so far', profit: 'Profit', revenue: 'Revenue', expenses: 'Expenses',
  profitMargin: 'Profit margin', activeEmployees: 'Active employees', upcomingPayroll: 'Next payroll', stepMoney: 'Record your first expense or sale',
  addBusinessExpense: 'Add business expense', addRevenue: 'Record revenue', noShiftToday: 'No shift today.', clockedInSince: 'Clocked in since {time}',
  breakMin: '{n} min break', scheduled: 'Scheduled', worked: 'Worked', completedShifts: 'Completed', rescheduled: 'Rescheduled',
  noShiftsWeek: 'No shifts this week.', nextShift: 'Next shift', payThisPeriod: 'Latest pay', requestsAndSwaps: 'Requests and swaps',
  expensesWaiting: 'Expenses waiting', 'swapsWaitingOnYou.one': 'A colleague is waiting for your answer on a swap',
  'swapsWaitingOnYou.other': '{n} swaps are waiting for your answer', requestChange: 'Request a change', swapShift: 'Swap a shift',
  addExpense: 'Add work expense', 'workingNow.one': '{n} working now', 'workingNow.other': '{n} working now',
  'approvalsWaiting.one': '{n} item is waiting for your approval', 'approvalsWaiting.other': '{n} items are waiting for your approval',
  todaysStaffing: 'Today\'s staffing', openShift: 'Open shift', noShiftsToday: 'No shifts today.', waitingForYou: 'Waiting for you',
  staff_scheduled: 'Scheduled', staff_working: 'Working now', staff_late: 'Late', staff_missed: 'Missed', staff_open: 'Open shifts',
  // schedule
  prevWeek: 'Previous week', nextWeek: 'Next week', copyLastWeek: 'Copy last week', publishWeek: 'Publish week', published: 'All published',
  allDepartments: 'All departments', scheduleHint: 'Drafts are only visible to managers until you publish them. Employees are notified when a schedule is published.',
  draft: 'Draft', addShift: 'Add shift', editShift: 'Edit shift', openShifts: 'Open shifts', noPeopleYet: 'No one to schedule yet',
  publishedToast: 'Published {n} shifts for {people} people', copyLastWeekQ: 'Copy last week\'s shifts?',
  copyLastWeekBody: 'They are added to this week as drafts. Any that break the schedule rules are skipped.', copiedToast: 'Copied {n} shifts ({skipped} skipped)',
  startTime: 'Start', endTime: 'End', overnightHint: 'An end time earlier than the start means the shift runs past midnight.', breakMinutes: 'Break (minutes)',
  publishNow: 'Publish now and notify the employee', cancelShift: 'Cancel shift', reasonForChange: 'Reason for the change',
  myAvailability: 'My availability', requestTimeOff: 'Request time off', noUpcomingShifts: 'No upcoming shifts', noUpcomingBody: 'Your manager hasn\'t published any shifts for you yet.',
  noPastShifts: 'No past shifts', giveAway: 'Give away', giveAwayBody: 'Colleagues can offer to take it; a manager approves.', offerShift: 'Offer shift',
  offerSent: 'Your shift is offered to colleagues', sendRequest: 'Send request', newDate: 'New date', requestSent: 'Request sent',
  noSwapOptions: 'No colleague has a shift that could be swapped without breaking the schedule rules.', yourShift: 'Your shift',
  askColleague: 'Ask colleague', swapWith: 'Swap with', swapSent: 'Swap request sent to your colleague', firstDayOff: 'First day off', lastDayOff: 'Last day off',
  availabilityBody: 'Times you can\'t work. Managers can\'t schedule you then.', alwaysAvailable: 'You haven\'t marked any times as unavailable.',
  addUnavailable: 'Add a time I can\'t work', chooseShift: 'Choose a shift',
  rule_inactive: 'This person isn\'t active.', rule_shift_too_long: 'The shift is longer than {limit} hours.', rule_overlap: 'It overlaps another shift.',
  rule_rest: 'There must be at least {limit} hours between shifts.', rule_unavailable: 'The person is unavailable or on time off then.',
  rule_weekly_hours: 'That would be {hours} hours this week; the limit is {limit}.',
  hist_created: 'Created', hist_updated: 'Changed', hist_reassigned: 'Reassigned', hist_swapped: 'Swapped', hist_cancelled: 'Cancelled',
  hist_published: 'Published', hist_unassigned: 'Opened up (time off)', hist_adjusted: 'Corrected', hist_archived: 'Archived', hist_restored: 'Restored', hist_deleted: 'Deleted',
  req_change: 'Shift change', req_time_off: 'Time off', req_offer: 'Shift given away', req_swap: 'Swap',
  // requests
  swapWithName: 'Swap with {name}', youGive: 'You give', youGet: 'You get', swapsForYou: 'Swaps waiting for you', swapAsk: '{name} wants to swap with you',
  shiftsUpForGrabs: 'Shifts colleagues are giving away', takeShift: 'Take shift', noRequests: 'No requests yet',
  noRequestsBody: 'Ask for a change, time off or a swap from any shift.', noSwaps: 'No swaps yet', cancelRequestQ: 'Cancel this request?',
  cancelRequest: 'Cancel request', requestCancelled: 'Request cancelled', cancelSwapQ: 'Cancel this swap?', cancelSwap: 'Cancel swap',
  swapCancelled: 'Swap cancelled', swapAcceptedToast: 'Accepted. A manager will approve the swap.', swapDeclinedToast: 'Swap declined',
  takenToast: 'You\'ve offered to take the shift. A manager will confirm.',
  // approvals
  shiftRequests: 'Shift requests', swaps: 'Swaps', employeeExpenses: 'Employee expenses', nothingToApprove: 'Nothing for you to approve.',
  allCaughtUp: 'All caught up', needsOwner: 'Needs owner approval', viewReceipt: 'View receipt', noReceipt: 'No receipt',
  markUnderReview: 'Mark under review', sentToOwner: 'Approved. It now needs the owner\'s approval.', approvedToast: 'Approved',
  reasonForEmployee: 'Reason (the employee will see this)', rejectedToast: 'Rejected',
  // attendance
  addRecord: 'Add record', missedShifts: 'Missed shifts', noMissed: 'No missed shifts.', totalWorked: 'Total worked', clockIn: 'Clock in',
  clockOut: 'Clock out', break: 'Break', late: 'Late', correct: 'Correct', noAttendance: 'No attendance records in this period.',
  notClockedIn: 'You are not clocked in', todaysShift: 'Today\'s shift', clockedOut: 'Clocked out', clockedIn: 'Clocked in',
  correctRecord: 'Correct attendance',
  // pay
  paidOn: 'Paid {date}', breakdown: 'Breakdown', hoursWorked: 'Hours worked', basePay: 'Base pay', overtime: 'Overtime', bonuses: 'Bonuses',
  deductions: 'Deductions', reimbursements: 'Expense repayments', netPay: 'Net pay', noPayYet: 'No pay statements yet',
  noPayYetBody: 'Your pay appears here once payroll is prepared.', payHistory: 'Pay history', gross: 'Gross', net: 'Net',
  payReadOnly: 'Pay records can\'t be changed here. If something looks wrong, ask your manager.',
  startPayroll: 'Start payroll', payrollNote: 'Payroll records and totals pay. It doesn\'t calculate taxes or send money.',
  'peopleN.one': '{n} person', 'peopleN.other': '{n} people', noPayrollRuns: 'No payroll yet', noPayrollRunsBody: 'Start a payroll to calculate pay from attendance and salaries.',
  startPayrollBody: 'Pick any day in the pay period. Hours, overtime, salaries and approved expenses are calculated automatically.',
  calculate: 'Calculate', dayInPeriod: 'A day in the pay period', allPayrolls: 'All payrolls', recalculate: 'Recalculate', finalize: 'Finalize',
  reopen: 'Reopen', markAllPaid: 'Mark all paid', runLocked: 'This payroll is paid and locked. Corrections go into the next payroll.',
  addLine: 'Add line', clearReview: 'Clear review', flagReview: 'Flag for review', markPaid: 'Mark paid', noPeopleInRun: 'No one to pay in this period',
  noPeopleInRunBody: 'Set pay rates on people\'s profiles, then recalculate.', finalizeQ: 'Finalize this payroll?',
  finalizeBody: 'Amounts are fixed and each person sees their pay as pending.', markAllPaidQ: 'Mark everyone as paid?',
  markAllPaidBody: 'The payroll locks and approved expenses are marked repaid.', bonus: 'Bonus', deduction: 'Deduction', adjustment: 'Adjustment',
  adjustmentHint: 'Adjustments can be negative (start with −).', noteForEmployee: 'Note for the employee',
  item_base: 'Base pay', item_overtime: 'Overtime', item_bonus: 'Bonus', item_deduction: 'Deduction', item_reimbursement: 'Expense repayment', item_adjustment: 'Adjustment',
  // expenses
  waitingApproval: 'Waiting for approval', approvedToRepay: 'Approved, to be repaid', noExpensesYet: 'No expenses yet',
  noExpensesYetBody: 'Add fuel, parking, supplies or other work costs and attach the receipt.', editExpense: 'Edit expense',
  submitForApproval: 'Submit for approval', saveDraft: 'Save draft', businessPurpose: 'Business purpose', expenseSubmitted: 'Expense submitted',
  draftSaved: 'Draft saved', fixResubmit: 'Fix and resubmit', deleteDraftQ: 'Delete this draft?',
  dec_review: 'Submitted / under review', dec_approve: 'Approved', dec_reject: 'Rejected', dec_reimburse: 'Repaid',
  // finance
  recurring: 'Recurring', budgets: 'Budgets', allCategories: 'All categories', 'countTotal.one': '{n} record', 'countTotal.other': '{n} records', countTotal: '{n} records',
  recurringShort: 'Recurring', noRevenueInRange: 'No revenue in this period.', noExpensesInRange: 'No expenses in this period.',
  archiveQ: 'Archive this record?', archiveBody: 'It leaves the totals but stays in the history. It can be restored.',
  revenueAmountHint: 'Refunds are subtracted automatically. Adjustments may be negative.',
  method_cash: 'Cash', method_card: 'Card', method_bank: 'Bank transfer', method_wallet: 'Mobile wallet', method_cheque: 'Cheque',
  everyNDays: 'Every {n} days', everyN_daily: 'Every {n} days', everyN_weekly: 'Every {n} weeks', everyN_monthly: 'Every {n} months',
  everyN_quarterly: 'Every {n} quarters', everyN_yearly: 'Every {n} years',
  freq_daily: 'Daily', freq_weekly: 'Weekly', freq_biweekly: 'Every two weeks', freq_monthly: 'Monthly', freq_quarterly: 'Quarterly', freq_yearly: 'Yearly', freq_custom: 'Custom',
  recurringIntro: 'Rent, generator, subscriptions… recorded automatically on each due date.', addRecurring: 'Add recurring expense',
  editRecurring: 'Edit recurring expense', recurringExpenses: 'Recurring expenses', nextOn: 'next {date}', stopped: 'stopped',
  noRecurring: 'No recurring expenses', noRecurringBody: 'Add rent or subscriptions once and they are recorded every period.',
  upcoming90: 'Coming up in the next 90 days', frequency: 'How often', repeatEvery: 'Repeat every', repeatEveryHint: 'For custom, the number of days.',
  firstPayment: 'First payment', lastPayment: 'Last payment', activeRecurring: 'Active',
  budgetsIntro: 'Monthly, quarterly or yearly limits. You are alerted at 80% and 100%.', addBudget: 'Add budget',
  overBy: 'Over by {a}', used: 'used', left: '{a} left', noBudgets: 'No budgets', noBudgetsBody: 'Set a limit for marketing, supplies, payroll or all spending.',
  budgetFor: 'Budget for', budget_category: 'A category', budget_payroll: 'Payroll', budget_total: 'All spending', budgetCategoryHint: 'Only for category budgets.',
  period_monthly: 'Monthly', period_quarterly: 'Quarterly', period_yearly: 'Yearly', activeBudget: 'Active', stopBudgetQ: 'Stop tracking this budget?', stopBudget: 'Stop',
  // analytics
  laborCost: 'Labour cost', payrollShare: 'Payroll share of revenue', comparedWith: 'Compared with {from} – {to}', smartAlerts: 'Smart alerts',
  payrollCost: 'Payroll cost', totalPayroll: 'Total payroll', avgEmployeeCost: 'Average cost per employee', overtimeCost: 'Overtime cost',
  revenueByCategory: 'Revenue by category', revenueVsExpenses: 'Revenue and expenses', profitLossOverTime: 'Profit and loss',
  expenseBreakdown: 'Where the money went', drillHint: 'Select a category to see its trend and transactions.', transactions: 'Transactions',
  shareOfExpenses: 'Share of expenses', previousPeriod: 'Previous period', noTransactions: 'No transactions.', monthlyTrend: 'Monthly trend',
  workforce: 'People and shifts', totalEmployees: 'Employees', newEmployees: 'New', terminatedEmployees: 'Left', shiftAnalytics: 'Shifts',
  scheduledHours: 'Scheduled hours', workedHours: 'Worked hours', shiftChanges: 'Shift changes', workforceHint: 'So far, {n}% of the hours scheduled up to now were worked.',
  // reports
  noReportsAvailable: 'No reports are available to you.', report: 'Report', printPdf: 'Print / PDF', 'rowsN.one': '{n} row', 'rowsN.other': '{n} rows',
  generatedAt: 'Generated {date}', preparingExport: 'Preparing your file…', exportReady: 'Your file is downloading',
  // notifications
  markAllRead: 'Mark all as read', noNotifications: 'You\'re all caught up.',
  // member profile
  openProfile: 'Open full profile', employment: 'Employment', terminate: 'End employment', reinstate: 'Reinstate', deletePermanently: 'Delete permanently',
  endedOn: 'Employment ended {date}', reportsTo: 'Reports to', workPhone: 'Work phone', personalDetails: 'Personal details',
  personalDetailsHint: 'Encrypted and visible only to this person and people allowed to see personal details.',
  emergencyName: 'Emergency contact', emergencyRelation: 'Relationship', emergencyPhone: 'Emergency phone', nationalId: 'National ID',
  birthDate: 'Date of birth', editProfile: 'Edit profile', payRateHistory: 'Pay rate history', changePay: 'Change pay', fromDate: 'from {date}',
  noPayRate: 'No pay rate set', changePayBody: 'The old rate is kept. The new one applies from the date you choose.',
  payRateHint: 'Per hour for hourly, per month for salaried.', effectiveFrom: 'Effective from', noShifts: 'No shifts.',
  uploadDocument: 'Upload document', documentsHint: 'Contracts and HR documents are private.', noDocuments: 'No documents.',
  terminateQ: 'End {name}\'s employment?', terminateBody: 'Sign-in is disabled, future shifts are cancelled and pending requests closed. Pay, expense and history records are all kept.',
  lastWorkingDay: 'Last working day', terminateConfirm: 'I understand this person will lose access', tickToConfirm: 'Tick the box to confirm.',
  terminatedToast: 'Employment ended. {n} future shifts were cancelled.', deletePermanentlyQ: 'Delete permanently?',
  deletePermanentlyBody: 'This removes {name} completely and can\'t be undone. It is only possible when no pay, expense or attendance records exist.',
  typeName: 'Type “{name}” to confirm', deleted: 'Deleted', doc_receipt: 'Receipt', doc_contract: 'Contract', doc_document: 'Document', doc_export: 'Export',
  // account
  notificationSettings: 'Notifications', notificationSettingsBody: 'You always see notifications in the app. Choose where else to receive them.',
  emailCopies: 'Email me a copy', smsCopies: 'Text me urgent updates', smsCopiesHint: 'Shift changes, swaps, time off and pay. Needs a verified phone.',
  myProfileDetails: 'My profile and emergency contact',
  // settings
  businessInfo: 'Business', schedulingRules: 'Scheduling rules', schedulingRulesBody: 'Checked every time a shift is created, changed or swapped.',
  maxWeeklyHours: 'Maximum hours per week', maxShiftHours: 'Maximum shift length (hours)', minRestHours: 'Minimum rest between shifts (hours)',
  payrollSettings: 'Payroll', payFrequency: 'Pay frequency', weekStartsOn: 'Week starts on', overtimeAfter: 'Overtime after (hours per week)', overtimeRate: 'Overtime rate',
  approvalRules: 'Approval rules', approvalRulesBody: 'Employee expenses are approved by a manager; larger ones also need the owner.', ownerApprovalOver: 'Owner approval above',
  alertThresholds: 'Smart alerts', alertThresholdsBody: 'You are notified when these are crossed.', alert_payroll: 'Payroll increase', alert_category: 'Category spending increase',
  alert_revenue: 'Revenue drop', alert_overtime: 'Overtime increase', alert_margin: 'Profit margin below', alert_large: 'Large expense from',
  alertField_payrollIncreasePct: 'Payroll increase', alertField_categoryIncreasePct: 'Category increase', alertField_revenueDropPct: 'Revenue drop',
  alertField_overtimeIncreasePct: 'Overtime increase', alertField_marginBelowPct: 'Margin below',
  authSettings: 'Sign-in security', authSettingsBody: 'Owner only.', requirePhone: 'Require a verified phone number',
  departmentsBody: 'A department manager sees and manages only their department.', managedBy: 'Managed by', noManager: 'No manager',
  noDepartments: 'No departments yet.', noLocations: 'No locations yet.', expenseCategories: 'Expense categories',
  expenseCategoriesBody: 'Built-in categories can be renamed or hidden, not deleted.', revenueCategories: 'Revenue categories', moreSettings: 'More',
  rolesPermissions: 'Roles and permissions', importOldApp: 'Import from the Business Expenses app',
  importOldAppBody: 'In the Business Expenses app, choose a period of “This year” or longer and press Export CSV, then choose that file here. Rejected expenses are skipped, and importing the same file again adds nothing twice.', chooseExportFile: 'Choose export file',
  currencyHint: 'Three letters, e.g. IQD or USD. Locked once money is recorded.', addDepartment: 'Add department', departmentManager: 'Department manager',
  departmentManagerHint: 'Leave empty to let all managers see this department.', addLocation: 'Add location', addCategory: 'Add category',
  nameAr: 'Name in Arabic', nameEn: 'Name in English', claimable: 'employees can claim', claimableLong: 'Employees can claim work expenses in this category',
  importResult: 'Imported {n} expenses and {s} salary records. Skipped {skipped} rejected; {again} were already imported.',
  importDone: 'Import finished', importBadFile: 'That file isn\'t a valid export.',
  kind_fixed: 'Fixed', kind_operating: 'Operating', kind_payroll: 'Payroll', kind_other: 'Other', kind_sale: 'Sales', kind_service: 'Services',
  kind_refund: 'Refund', kind_adjustment: 'Adjustment',
  // search
  sg_employees: 'People', sg_departments: 'Departments', sg_shifts: 'Shifts', sg_employeeExpenses: 'Employee expenses',
  sg_businessExpenses: 'Business expenses', sg_revenue: 'Revenue', sg_payroll: 'Payroll', sg_reports: 'Reports',
  // errors
  'e.amount': 'Enter an amount above zero.', 'e.invalid_category': 'Choose a category.', 'e.invalid_receipt': 'Upload the receipt again.',
  'e.future_date': 'The date can\'t be in the future.', 'e.locked': 'This can\'t be changed any more.', 'e.not_pending': 'This has already been decided.',
  'e.reason_required': 'Give a reason.', 'e.not_approved': 'Only approved expenses can be repaid.', 'e.in_payroll': 'This is being repaid through payroll.',
  'e.run_locked': 'This payroll is locked.', 'e.needs_review': 'Clear the review flag first.', 'e.period_overlap': 'Another payroll already covers part of this period.',
  'e.period_locked': 'This time is in a paid payroll and can\'t be changed.', 'e.already_clocked_in': 'You are already clocked in.',
  'e.not_clocked_in': 'You are not clocked in.', 'e.invalid_break': 'The break is longer than the time worked.', 'e.invalid_times': 'Check the times.',
  'e.shift_closed': 'This shift can no longer be changed.', 'e.already_requested': 'There is already a pending request for this shift.',
  'e.shift_changed': 'The shift changed since the request was made.', 'e.no_taker': 'Nobody has taken this shift yet.',
  'e.not_available': 'This shift has already been taken.', 'e.invalid_taker': 'Choose a colleague.', 'e.shift_required': 'Choose a shift.',
  'e.file_type': 'Upload a photo (JPEG, PNG, WebP) or a PDF.', 'e.file_too_large': 'The file is too large.', 'e.empty_file': 'The file is empty.',
  'e.confirm_mismatch': 'Type the full name exactly.', 'e.has_records': 'This person has records that must be kept. Keep them archived.',
  'e.currency_locked': 'The currency can\'t change after money has been recorded.', 'e.invalid_timezone': 'Unknown time zone.',
  'e.duplicate_name': 'That name is already used.', 'e.duplicate_budget': 'There is already a budget for this.', 'e.invalid_manager': 'Choose a manager.',
  'e.invalid_department': 'Choose a department.', 'e.invalid_location': 'Choose a location.', 'e.invalid_member': 'Choose someone from your team.',
  'e.invalid_amount': 'Check the amount.', 'e.range_too_long': 'Choose a shorter date range.', 'e.invalid_range': 'The end date must be after the start.',
  'e.archived': 'Restore this record first.', 'e.interval_required': 'Choose how many days between payments.', 'e.invalid_budget': 'Category budgets need a category.',
  // audit log
  'a.attendance.added': '{actor} added attendance for {target}', 'a.attendance.adjusted': '{actor} corrected attendance for {target}',
  'a.attendance.clock_in': '{actor} clocked in', 'a.attendance.clock_out': '{actor} clocked out',
  'a.auth.login': '{actor} signed in', 'a.auth.login_recovery_code': '{actor} signed in with a recovery code', 'a.auth.logout_all': '{actor} signed out everywhere',
  'a.auth.logout_other_devices': '{actor} signed out other devices', 'a.auth.password_changed': '{actor} changed their password',
  'a.auth.password_reset': '{actor} reset their password', 'a.auth.password_reset_requested': 'A password reset was requested for {actor}',
  'a.auth.email_verified': '{actor} verified their email', 'a.auth.phone_verified': '{actor} verified their phone',
  'a.budget.created': '{actor} added a budget', 'a.budget.updated': '{actor} changed a budget', 'a.business.settings_updated': '{actor} changed the business settings',
  'a.business_expense.created': '{actor} recorded a business expense', 'a.business_expense.updated': '{actor} edited a business expense',
  'a.business_expense.archived': '{actor} archived a business expense', 'a.business_expense.restored': '{actor} restored a business expense',
  'a.category.created': '{actor} added a category', 'a.category.updated': '{actor} changed a category',
  'a.department.created': '{actor} added a department', 'a.department.updated': '{actor} changed a department',
  'a.location.created': '{actor} added a location', 'a.location.updated': '{actor} changed a location',
  'a.document.uploaded': '{actor} uploaded a document', 'a.document.archived': '{actor} archived a document',
  'a.employee_expense.created': '{actor} submitted an expense', 'a.employee_expense.review': '{actor} put an expense under review',
  'a.employee_expense.approved': '{actor} approved an expense', 'a.employee_expense.approved_step1': '{actor} approved an expense for the owner\'s review',
  'a.employee_expense.reject': '{actor} rejected an expense', 'a.employee_expense.reimbursed': '{actor} marked an expense as repaid',
  'a.import.expenses_app': '{actor} imported records from the Business Expenses app',
  'a.member.archived': '{actor} archived {target}', 'a.member.deleted': '{actor} permanently deleted a person', 'a.member.pay_changed': '{actor} changed {target}\'s pay',
  'a.member.profile_updated': '{actor} updated {target}\'s profile', 'a.member.reinstated': '{actor} reinstated {target}', 'a.member.terminated': '{actor} ended {target}\'s employment',
  'a.payroll.run_created': '{actor} started a payroll', 'a.payroll.recalculated': '{actor} recalculated a payroll', 'a.payroll.finalized': '{actor} finalized a payroll',
  'a.payroll.reopened': '{actor} reopened a payroll', 'a.payroll.paid': '{actor} marked pay as paid', 'a.payroll.flagged_for_review': '{actor} flagged pay for review',
  'a.payroll.review_cleared': '{actor} cleared a pay review', 'a.payroll.item_removed': '{actor} removed a payroll line', 'a.payroll.bonus_added': '{actor} added a bonus',
  'a.payroll.deduction_added': '{actor} added a deduction', 'a.payroll.adjustment_added': '{actor} added a pay adjustment',
  'a.recurring_expense.created': '{actor} added a recurring expense', 'a.recurring_expense.updated': '{actor} changed a recurring expense',
  'a.report.exported': '{actor} exported a report', 'a.revenue.created': '{actor} recorded revenue', 'a.revenue.updated': '{actor} edited revenue',
  'a.revenue.archived': '{actor} archived revenue', 'a.revenue.restored': '{actor} restored revenue', 'a.schedule.published': '{actor} published the schedule',
  'a.shift.created': '{actor} added a shift', 'a.shift.updated': '{actor} changed a shift', 'a.shift.cancelled': '{actor} cancelled a shift',
  'a.shift.assigned': '{actor} assigned a shift', 'a.shift.changed': '{actor} changed a shift',
  'a.shift_request.created': '{actor} asked for a shift change', 'a.shift_request.approved': '{actor} approved a shift request',
  'a.shift_request.rejected': '{actor} declined a shift request', 'a.shift_request.cancelled': '{actor} cancelled a shift request',
  'a.swap.requested': '{actor} asked for a swap', 'a.swap.accepted_by_colleague': '{actor} accepted a swap', 'a.swap.declined_by_colleague': '{actor} declined a swap',
  'a.swap.approved': '{actor} approved a swap', 'a.swap.rejected': '{actor} declined a swap', 'a.swap.cancelled': '{actor} cancelled a swap',
  'a.time_off.approved': '{actor} approved time off', 'a.time_off.rejected': '{actor} declined time off',
  filter_shift: 'Shifts', filter_swap: 'Swaps', filter_payroll: 'Payroll', filter_employee_expense: 'Employee expenses',
  filter_business_expense: 'Business expenses', filter_revenue: 'Revenue', filter_attendance: 'Attendance', filter_auth: 'Sign-ins',
  'e.invalid_shift': 'Choose a valid shift.', 'e.invalid_document': 'Upload the file again.', 'e.no_contact': 'This person has no verified email or phone.',
  'e.import_bad_file': 'That file isn\'t an export from the Business Expenses app.', 'e.invalid_value': 'Check the value.', 'e.range_required': 'Choose a date range.', 'e.unknown_permission': 'Unknown permission.',
  // notification texts
  'n.invitation.accepted': '{name} accepted your invitation', 'n.role.changed': 'Your role has changed', 'n.member.suspended': 'Your access was suspended',
  'n.member.active': 'Your access was restored', 'n.shift.assigned': 'You have a new shift', 'n.shift.changed': 'One of your shifts changed',
  'n.shift.cancelled': 'One of your shifts was cancelled', 'n.schedule.published': 'Your new schedule is ready ({count} shifts)',
  'n.shift.offered': 'A colleague offered you a shift', 'n.shift.offer_taken': 'Someone offered to take your shift',
  'n.request.new': 'A shift request needs your review', 'n.request.approved': 'Your shift request was approved', 'n.request.rejected': 'Your shift request was declined',
  'n.time_off.approved': 'Your time off was approved', 'n.time_off.rejected': 'Your time off was declined',
  'n.swap.requested': 'A colleague wants to swap shifts with you', 'n.swap.accepted': 'Your swap was accepted and awaits approval',
  'n.swap.awaiting_approval': 'A shift swap needs your approval', 'n.swap.approved': 'Your shift swap was approved', 'n.swap.rejected': 'Your shift swap was declined',
  'n.swap.cancelled': 'A shift swap was cancelled', 'n.expense.submitted': 'An expense of {amount} is waiting for review',
  'n.expense.owner_approval': 'An expense of {amount} needs your approval', 'n.expense.approved': 'Your expense of {amount} was approved',
  'n.expense.rejected': 'Your expense was declined: {reason}', 'n.expense.reimbursed': 'Your expense of {amount} was repaid',
  'n.finance.large_expense': 'A large expense of {amount} was recorded', 'n.salary.pending': 'Your pay for this period is ready: {net}',
  'n.salary.paid': 'You were paid {net}',
  'n.alert.payroll_increase': 'Payroll is up {pct}% compared with last month', 'n.alert.revenue_drop': 'Revenue is down {pct}% compared with last month',
  'n.alert.category_increase': '{nameEn} spending is up {pct}%', 'n.alert.overtime_increase': 'Overtime is up {pct}%',
  'n.alert.margin_low': 'Profit margin fell to {margin}% (your threshold is {threshold}%)', 'n.alert.budget_over': 'The {categoryEn} budget was exceeded',
  'n.alert.budget_near': 'The {categoryEn} budget is {used}% used',
};

export const ar = {
  analytics: 'التحليلات', finance: 'المالية', schedule: 'الجدول', mySchedule: 'جدولي', approvals: 'الموافقات',
  myRequests: 'طلباتي', attendance: 'الحضور', myPay: 'راتبي', myExpenses: 'مصاريفي', payroll: 'الرواتب',
  reports: 'التقارير', settings: 'الإعدادات', notifications: 'الإشعارات', search: 'بحث', searchEverything: 'ابحث في الأشخاص والمناوبات والمصاريف والتقارير…',
  noResults: 'لا توجد نتائج.', overview: 'نظرة عامة', pay: 'الأجر', shifts: 'المناوبات', documents: 'المستندات', profile: 'الملف الشخصي',
  add: 'إضافة', edit: 'تعديل', delete: 'حذف', remove: 'إزالة', open: 'فتح', archive: 'أرشفة', archived: 'مؤرشف', details: 'التفاصيل',
  history: 'السجل', reason: 'السبب', note: 'ملاحظة', notes: 'ملاحظات', name: 'الاسم', type: 'النوع', date: 'التاريخ', amount: 'المبلغ', total: 'المجموع',
  status: 'الحالة', period: 'الفترة', month: 'الشهر', person: 'الشخص', description: 'الوصف', category: 'الفئة', share: 'النسبة',
  current: 'الحالي', today: 'اليوم', thisWeek: 'هذا الأسبوع', upcoming: 'القادمة', previous: 'السابقة', other: 'أخرى', everyone: 'الجميع',
  seeAll: 'عرض الكل', review: 'مراجعة', dismiss: 'إخفاء', accept: 'قبول', decline: 'رفض', approve: 'موافقة', reject: 'رفض',
  noData: 'لا توجد بيانات لهذه الفترة.', hoursShort: 'س', hoursCol: 'الساعات', points: 'نقطة', vsPrevious: 'مقارنة بالفترة السابقة',
  showTable: 'جدول', showChart: 'رسم', chartHint: 'استخدم مفاتيح الأسهم للتنقل بين القيم.', dateRange: 'الفترة',
  attachFile: 'إرفاق صورة أو PDF', uploading: 'جارٍ الرفع…', uploaded: 'تم الرفع', icon: 'الرمز', address: 'العنوان', location: 'الموقع',
  vendor: 'الجهة', customerSource: 'العميل / المصدر', paymentMethod: 'طريقة الدفع', receipt: 'الوصل', receiptDocument: 'الوصل أو المستند',
  timezone: 'المنطقة الزمنية', currency: 'العملة', decimals: 'منازل عشرية', departments: 'الأقسام', locations: 'المواقع',
  range_today: 'اليوم', range_yesterday: 'أمس', range_thisWeek: 'هذا الأسبوع', range_lastWeek: 'الأسبوع الماضي', range_thisMonth: 'هذا الشهر',
  range_lastMonth: 'الشهر الماضي', range_thisQuarter: 'هذا الربع', range_thisYear: 'هذه السنة', range_lastYear: 'السنة الماضية', range_custom: 'فترة مخصصة',
  st_pending: 'قيد الانتظار', st_submitted: 'مُرسل', st_under_review: 'قيد المراجعة', st_pending_peer: 'بانتظار الزميل',
  st_pending_approval: 'بانتظار الموافقة', st_review: 'يحتاج مراجعة', st_draft: 'مسودة', st_approved: 'موافق عليه', st_completed: 'مكتمل',
  st_paid: 'مدفوع', st_reimbursed: 'تم التعويض', st_finalized: 'مُعتمد', st_scheduled: 'مجدول', st_working: 'يعمل الآن', st_done: 'انتهى',
  st_rejected: 'مرفوض', st_cancelled: 'ملغى', st_missed: 'فائت', st_late: 'متأخر', st_open: 'مفتوح', st_upcoming: 'قادم', st_rescheduled: 'أُعيدت جدولته',
  howIsBusiness: 'كيف حال نشاطي التجاري؟', monthToDate: 'هذا الشهر حتى الآن', profit: 'الربح', revenue: 'الإيرادات', expenses: 'المصاريف',
  profitMargin: 'هامش الربح', activeEmployees: 'الموظفون النشطون', upcomingPayroll: 'الرواتب القادمة', stepMoney: 'سجّل أول مصروف أو مبيعات',
  addBusinessExpense: 'إضافة مصروف للنشاط', addRevenue: 'تسجيل إيراد', noShiftToday: 'لا توجد مناوبة اليوم.', clockedInSince: 'مسجّل الحضور منذ {time}',
  breakMin: 'استراحة {n} دقيقة', scheduled: 'مجدول', worked: 'منجز', completedShifts: 'مكتملة', rescheduled: 'أُعيدت جدولتها',
  noShiftsWeek: 'لا توجد مناوبات هذا الأسبوع.', nextShift: 'المناوبة القادمة', payThisPeriod: 'آخر راتب', requestsAndSwaps: 'الطلبات والتبديلات',
  expensesWaiting: 'مصاريف بالانتظار', 'swapsWaitingOnYou.one': 'زميل ينتظر ردك على تبديل', 'swapsWaitingOnYou.other': '{n} تبديلات بانتظار ردك',
  requestChange: 'طلب تغيير', swapShift: 'تبديل مناوبة', addExpense: 'إضافة مصروف عمل',
  'workingNow.one': '{n} يعمل الآن', 'workingNow.other': '{n} يعملون الآن',
  'approvalsWaiting.one': 'عنصر واحد بانتظار موافقتك', 'approvalsWaiting.two': 'عنصران بانتظار موافقتك', 'approvalsWaiting.other': '{n} عناصر بانتظار موافقتك',
  todaysStaffing: 'طاقم اليوم', openShift: 'مناوبة مفتوحة', noShiftsToday: 'لا توجد مناوبات اليوم.', waitingForYou: 'بانتظارك',
  staff_scheduled: 'مجدولون', staff_working: 'يعملون الآن', staff_late: 'متأخرون', staff_missed: 'غائبون', staff_open: 'مناوبات مفتوحة',
  prevWeek: 'الأسبوع السابق', nextWeek: 'الأسبوع التالي', copyLastWeek: 'نسخ الأسبوع الماضي', publishWeek: 'نشر الأسبوع', published: 'كلها منشورة',
  allDepartments: 'كل الأقسام', scheduleHint: 'المسودات لا يراها إلا المدراء حتى تنشرها، ويُبلَّغ الموظفون عند نشر الجدول.',
  draft: 'مسودة', addShift: 'إضافة مناوبة', editShift: 'تعديل المناوبة', openShifts: 'مناوبات مفتوحة', noPeopleYet: 'لا يوجد أحد لجدولته بعد',
  publishedToast: 'نُشرت {n} مناوبات لـ {people} أشخاص', copyLastWeekQ: 'نسخ مناوبات الأسبوع الماضي؟',
  copyLastWeekBody: 'تُضاف إلى هذا الأسبوع كمسودات، ويُتجاوز ما يخالف قواعد الجدول.', copiedToast: 'نُسخت {n} مناوبات (تُجووز {skipped})',
  startTime: 'البداية', endTime: 'النهاية', overnightHint: 'وقت نهاية قبل البداية يعني أن المناوبة تمتد بعد منتصف الليل.', breakMinutes: 'الاستراحة (دقائق)',
  publishNow: 'انشرها الآن وأبلغ الموظف', cancelShift: 'إلغاء المناوبة', reasonForChange: 'سبب التغيير',
  myAvailability: 'أوقات عدم التوفر', requestTimeOff: 'طلب إجازة', noUpcomingShifts: 'لا توجد مناوبات قادمة', noUpcomingBody: 'لم ينشر مديرك أي مناوبات لك بعد.',
  noPastShifts: 'لا توجد مناوبات سابقة', giveAway: 'التنازل عنها', giveAwayBody: 'يمكن لزملائك أخذها، ويوافق عليها مدير.', offerShift: 'عرض المناوبة',
  offerSent: 'عُرضت مناوبتك على الزملاء', sendRequest: 'إرسال الطلب', newDate: 'التاريخ الجديد', requestSent: 'أُرسل الطلب',
  noSwapOptions: 'لا يملك أي زميل مناوبة يمكن تبديلها دون مخالفة قواعد الجدول.', yourShift: 'مناوبتك',
  askColleague: 'اسأل الزميل', swapWith: 'التبديل مع', swapSent: 'أُرسل طلب التبديل إلى زميلك', firstDayOff: 'أول يوم إجازة', lastDayOff: 'آخر يوم إجازة',
  availabilityBody: 'أوقات لا تستطيع العمل فيها، ولا يمكن جدولتك خلالها.', alwaysAvailable: 'لم تحدد أي أوقات عدم توفر.',
  addUnavailable: 'إضافة وقت لا أستطيع العمل فيه', chooseShift: 'اختر مناوبة',
  rule_inactive: 'هذا الشخص غير نشط.', rule_shift_too_long: 'المناوبة أطول من {limit} ساعة.', rule_overlap: 'تتداخل مع مناوبة أخرى.',
  rule_rest: 'يجب ألا تقل الفترة بين المناوبتين عن {limit} ساعات.', rule_unavailable: 'الشخص غير متاح أو في إجازة في ذلك الوقت.',
  rule_weekly_hours: 'سيصبح المجموع {hours} ساعة هذا الأسبوع، والحد {limit}.',
  hist_created: 'أُنشئت', hist_updated: 'عُدّلت', hist_reassigned: 'نُقلت لشخص آخر', hist_swapped: 'بُدّلت', hist_cancelled: 'أُلغيت',
  hist_published: 'نُشرت', hist_unassigned: 'فُتحت (إجازة)', hist_adjusted: 'صُحّحت', hist_archived: 'أُرشفت', hist_restored: 'استُعيدت', hist_deleted: 'حُذفت',
  req_change: 'تغيير مناوبة', req_time_off: 'إجازة', req_offer: 'تنازل عن مناوبة', req_swap: 'تبديل',
  swapWithName: 'تبديل مع {name}', youGive: 'تعطي', youGet: 'تأخذ', swapsForYou: 'تبديلات بانتظارك', swapAsk: 'يريد {name} التبديل معك',
  shiftsUpForGrabs: 'مناوبات يتنازل عنها الزملاء', takeShift: 'أخذ المناوبة', noRequests: 'لا توجد طلبات بعد',
  noRequestsBody: 'اطلب تغييراً أو إجازة أو تبديلاً من أي مناوبة.', noSwaps: 'لا توجد تبديلات بعد', cancelRequestQ: 'إلغاء هذا الطلب؟',
  cancelRequest: 'إلغاء الطلب', requestCancelled: 'أُلغي الطلب', cancelSwapQ: 'إلغاء هذا التبديل؟', cancelSwap: 'إلغاء التبديل',
  swapCancelled: 'أُلغي التبديل', swapAcceptedToast: 'تم القبول، وسيوافق مدير على التبديل.', swapDeclinedToast: 'رُفض التبديل',
  takenToast: 'عرضت أخذ المناوبة، وسيؤكدها مدير.',
  shiftRequests: 'طلبات المناوبات', swaps: 'التبديلات', employeeExpenses: 'مصاريف الموظفين', nothingToApprove: 'لا يوجد ما تحتاج الموافقة عليه.',
  allCaughtUp: 'لا شيء بانتظارك', needsOwner: 'يحتاج موافقة المالك', viewReceipt: 'عرض الوصل', noReceipt: 'بلا وصل',
  markUnderReview: 'وضعه قيد المراجعة', sentToOwner: 'تمت الموافقة، والآن يحتاج موافقة المالك.', approvedToast: 'تمت الموافقة',
  reasonForEmployee: 'السبب (سيراه الموظف)', rejectedToast: 'تم الرفض',
  addRecord: 'إضافة سجل', missedShifts: 'مناوبات فائتة', noMissed: 'لا توجد مناوبات فائتة.', totalWorked: 'مجموع ساعات العمل', clockIn: 'تسجيل الحضور',
  clockOut: 'تسجيل الانصراف', break: 'استراحة', late: 'تأخير', correct: 'تصحيح', noAttendance: 'لا توجد سجلات حضور في هذه الفترة.',
  notClockedIn: 'لم تسجّل حضورك', todaysShift: 'مناوبة اليوم', clockedOut: 'سُجّل الانصراف', clockedIn: 'سُجّل الحضور', correctRecord: 'تصحيح الحضور',
  paidOn: 'دُفع {date}', breakdown: 'التفاصيل', hoursWorked: 'ساعات العمل', basePay: 'الأجر الأساسي', overtime: 'العمل الإضافي', bonuses: 'المكافآت',
  deductions: 'الاستقطاعات', reimbursements: 'تعويض المصاريف', netPay: 'صافي الراتب', noPayYet: 'لا توجد كشوف رواتب بعد',
  noPayYetBody: 'يظهر راتبك هنا بعد إعداد الرواتب.', payHistory: 'سجل الرواتب', gross: 'الإجمالي', net: 'الصافي',
  payReadOnly: 'لا يمكن تعديل سجلات الرواتب هنا. إذا بدا شيء غير صحيح فاسأل مديرك.',
  startPayroll: 'بدء الرواتب', payrollNote: 'يسجّل هذا القسم الرواتب ومجاميعها، ولا يحسب الضرائب ولا يحوّل الأموال.',
  'peopleN.one': 'شخص واحد', 'peopleN.two': 'شخصان', 'peopleN.few': '{n} أشخاص', 'peopleN.many': '{n} شخصاً', 'peopleN.other': '{n} شخص',
  noPayrollRuns: 'لا توجد رواتب بعد', noPayrollRunsBody: 'ابدأ الرواتب لحساب الأجور من الحضور والرواتب الثابتة.',
  startPayrollBody: 'اختر أي يوم في فترة الدفع، وتُحسب الساعات والعمل الإضافي والرواتب والمصاريف الموافق عليها تلقائياً.',
  calculate: 'احسب', dayInPeriod: 'يوم ضمن فترة الدفع', allPayrolls: 'كل الرواتب', recalculate: 'إعادة الحساب', finalize: 'اعتماد',
  reopen: 'إعادة فتح', markAllPaid: 'تأشير الكل كمدفوع', runLocked: 'هذه الرواتب مدفوعة ومقفلة، وتُضاف التصحيحات إلى الرواتب التالية.',
  addLine: 'إضافة بند', clearReview: 'إزالة المراجعة', flagReview: 'تأشير للمراجعة', markPaid: 'تأشير كمدفوع', noPeopleInRun: 'لا يوجد من يُدفع له في هذه الفترة',
  noPeopleInRunBody: 'حدّد الأجور في ملفات الأشخاص ثم أعد الحساب.', finalizeQ: 'اعتماد هذه الرواتب؟',
  finalizeBody: 'تُثبّت المبالغ ويرى كل شخص راتبه قيد الانتظار.', markAllPaidQ: 'تأشير الجميع كمدفوعين؟',
  markAllPaidBody: 'تُقفل الرواتب وتُعلَّم المصاريف الموافق عليها كمعوَّضة.', bonus: 'مكافأة', deduction: 'استقطاع', adjustment: 'تسوية',
  adjustmentHint: 'يمكن أن تكون التسوية سالبة (ابدأ بـ −).', noteForEmployee: 'ملاحظة للموظف',
  item_base: 'الأجر الأساسي', item_overtime: 'العمل الإضافي', item_bonus: 'مكافأة', item_deduction: 'استقطاع', item_reimbursement: 'تعويض مصروف', item_adjustment: 'تسوية',
  waitingApproval: 'بانتظار الموافقة', approvedToRepay: 'موافق عليها بانتظار التعويض', noExpensesYet: 'لا توجد مصاريف بعد',
  noExpensesYetBody: 'أضف الوقود والمواقف والمستلزمات وغيرها من تكاليف العمل وأرفق الوصل.', editExpense: 'تعديل المصروف',
  submitForApproval: 'إرسال للموافقة', saveDraft: 'حفظ كمسودة', businessPurpose: 'غرض العمل', expenseSubmitted: 'أُرسل المصروف',
  draftSaved: 'حُفظت المسودة', fixResubmit: 'تصحيح وإعادة الإرسال', deleteDraftQ: 'حذف هذه المسودة؟',
  dec_review: 'أُرسل / قيد المراجعة', dec_approve: 'تمت الموافقة', dec_reject: 'رُفض', dec_reimburse: 'عُوّض',
  recurring: 'المتكررة', budgets: 'الميزانيات', allCategories: 'كل الفئات', 'countTotal.one': 'سجل واحد', 'countTotal.two': 'سجلان', 'countTotal.few': '{n} سجلات', 'countTotal.other': '{n} سجل', countTotal: '{n} سجل',
  recurringShort: 'متكرر', noRevenueInRange: 'لا توجد إيرادات في هذه الفترة.', noExpensesInRange: 'لا توجد مصاريف في هذه الفترة.',
  archiveQ: 'أرشفة هذا السجل؟', archiveBody: 'يخرج من المجاميع ويبقى في السجل، ويمكن استعادته.',
  revenueAmountHint: 'تُطرح المرتجعات تلقائياً، ويمكن أن تكون التسويات سالبة.',
  method_cash: 'نقداً', method_card: 'بطاقة', method_bank: 'تحويل مصرفي', method_wallet: 'محفظة إلكترونية', method_cheque: 'صك',
  everyNDays: 'كل {n} أيام', everyN_daily: 'كل {n} أيام', everyN_weekly: 'كل {n} أسابيع', everyN_monthly: 'كل {n} أشهر',
  everyN_quarterly: 'كل {n} أرباع', everyN_yearly: 'كل {n} سنوات',
  freq_daily: 'يومي', freq_weekly: 'أسبوعي', freq_biweekly: 'كل أسبوعين', freq_monthly: 'شهري', freq_quarterly: 'ربع سنوي', freq_yearly: 'سنوي', freq_custom: 'مخصص',
  recurringIntro: 'الإيجار والمولّدة والاشتراكات… تُسجَّل تلقائياً في كل موعد.', addRecurring: 'إضافة مصروف متكرر',
  editRecurring: 'تعديل المصروف المتكرر', recurringExpenses: 'المصاريف المتكررة', nextOn: 'التالي {date}', stopped: 'متوقف',
  noRecurring: 'لا توجد مصاريف متكررة', noRecurringBody: 'أضف الإيجار أو الاشتراكات مرة واحدة وتُسجَّل في كل فترة.',
  upcoming90: 'القادم خلال ٩٠ يوماً', frequency: 'التكرار', repeatEvery: 'التكرار كل', repeatEveryHint: 'للمخصص: عدد الأيام.',
  firstPayment: 'أول دفعة', lastPayment: 'آخر دفعة', activeRecurring: 'فعّال',
  budgetsIntro: 'حدود شهرية أو ربعية أو سنوية، وتصلك تنبيهات عند ٨٠٪ و١٠٠٪.', addBudget: 'إضافة ميزانية',
  overBy: 'تجاوز بـ {a}', used: 'مستخدم', left: 'متبقٍّ {a}', noBudgets: 'لا توجد ميزانيات', noBudgetsBody: 'حدّد سقفاً للتسويق أو المستلزمات أو الرواتب أو كل الإنفاق.',
  budgetFor: 'الميزانية لـ', budget_category: 'فئة', budget_payroll: 'الرواتب', budget_total: 'كل الإنفاق', budgetCategoryHint: 'لميزانيات الفئات فقط.',
  period_monthly: 'شهرية', period_quarterly: 'ربعية', period_yearly: 'سنوية', activeBudget: 'فعّالة', stopBudgetQ: 'إيقاف متابعة هذه الميزانية؟', stopBudget: 'إيقاف',
  laborCost: 'تكلفة العمالة', payrollShare: 'نسبة الرواتب من الإيرادات', comparedWith: 'مقارنة بالفترة {from} – {to}', smartAlerts: 'تنبيهات ذكية',
  payrollCost: 'تكلفة الرواتب', totalPayroll: 'مجموع الرواتب', avgEmployeeCost: 'متوسط تكلفة الموظف', overtimeCost: 'تكلفة العمل الإضافي',
  revenueByCategory: 'الإيرادات حسب الفئة', revenueVsExpenses: 'الإيرادات والمصاريف', profitLossOverTime: 'الأرباح والخسائر',
  expenseBreakdown: 'أين ذهبت الأموال', drillHint: 'اختر فئة لعرض اتجاهها وعملياتها.', transactions: 'العمليات',
  shareOfExpenses: 'النسبة من المصاريف', previousPeriod: 'الفترة السابقة', noTransactions: 'لا توجد عمليات.', monthlyTrend: 'الاتجاه الشهري',
  workforce: 'الأشخاص والمناوبات', totalEmployees: 'الموظفون', newEmployees: 'جدد', terminatedEmployees: 'غادروا', shiftAnalytics: 'المناوبات',
  scheduledHours: 'الساعات المجدولة', workedHours: 'الساعات المنجزة', shiftChanges: 'تغييرات المناوبات', workforceHint: 'حتى الآن أُنجز {n}٪ من الساعات المجدولة لغاية اليوم.',
  noReportsAvailable: 'لا توجد تقارير متاحة لك.', report: 'التقرير', printPdf: 'طباعة / PDF', 'rowsN.one': 'صف واحد', 'rowsN.other': '{n} صف',
  generatedAt: 'أُنشئ في {date}', preparingExport: 'جارٍ تجهيز الملف…', exportReady: 'جارٍ تنزيل الملف',
  markAllRead: 'تعليم الكل كمقروء', noNotifications: 'لا شيء جديد.',
  openProfile: 'فتح الملف الكامل', employment: 'التوظيف', terminate: 'إنهاء الخدمة', reinstate: 'إعادة التعيين', deletePermanently: 'حذف نهائي',
  endedOn: 'انتهت الخدمة {date}', reportsTo: 'يتبع إلى', workPhone: 'هاتف العمل', personalDetails: 'البيانات الشخصية',
  personalDetailsHint: 'مشفّرة، ولا يراها إلا صاحبها ومن يُسمح لهم برؤية البيانات الشخصية.',
  emergencyName: 'جهة الاتصال للطوارئ', emergencyRelation: 'صلة القرابة', emergencyPhone: 'هاتف الطوارئ', nationalId: 'رقم الهوية',
  birthDate: 'تاريخ الميلاد', editProfile: 'تعديل الملف', payRateHistory: 'سجل الأجور', changePay: 'تغيير الأجر', fromDate: 'من {date}',
  noPayRate: 'لم يُحدد أجر', changePayBody: 'يُحتفظ بالأجر القديم، ويُطبّق الجديد من التاريخ الذي تختاره.',
  payRateHint: 'للساعة في الأجر بالساعة، وشهرياً للراتب الثابت.', effectiveFrom: 'يسري من', noShifts: 'لا توجد مناوبات.',
  uploadDocument: 'رفع مستند', documentsHint: 'العقود ومستندات الموظفين خاصة.', noDocuments: 'لا توجد مستندات.',
  terminateQ: 'إنهاء خدمة {name}؟', terminateBody: 'يُعطَّل تسجيل الدخول وتُلغى المناوبات القادمة والطلبات المعلقة، وتبقى سجلات الرواتب والمصاريف والسجل كاملة.',
  lastWorkingDay: 'آخر يوم عمل', terminateConfirm: 'أفهم أن هذا الشخص سيفقد الوصول', tickToConfirm: 'أشّر على المربع للتأكيد.',
  terminatedToast: 'انتهت الخدمة وأُلغيت {n} مناوبات قادمة.', deletePermanentlyQ: 'حذف نهائي؟',
  deletePermanentlyBody: 'يزيل هذا {name} بالكامل ولا يمكن التراجع عنه، ويُسمح به فقط عند عدم وجود سجلات رواتب أو مصاريف أو حضور.',
  typeName: 'اكتب «{name}» للتأكيد', deleted: 'تم الحذف', doc_receipt: 'وصل', doc_contract: 'عقد', doc_document: 'مستند', doc_export: 'ملف مُصدَّر',
  notificationSettings: 'الإشعارات', notificationSettingsBody: 'تظهر الإشعارات دائماً في التطبيق. اختر أين تصلك أيضاً.',
  emailCopies: 'أرسل لي نسخة بالبريد', smsCopies: 'أرسل لي التحديثات العاجلة برسالة نصية', smsCopiesHint: 'تغييرات المناوبات والتبديلات والإجازات والرواتب، ويتطلب هاتفاً متحققاً منه.',
  myProfileDetails: 'ملفي وجهة الاتصال للطوارئ',
  businessInfo: 'النشاط التجاري', schedulingRules: 'قواعد الجدولة', schedulingRulesBody: 'تُفحص عند كل إنشاء أو تعديل أو تبديل لمناوبة.',
  maxWeeklyHours: 'أقصى ساعات في الأسبوع', maxShiftHours: 'أقصى طول للمناوبة (ساعات)', minRestHours: 'أقل راحة بين المناوبات (ساعات)',
  payrollSettings: 'الرواتب', payFrequency: 'دورية الدفع', weekStartsOn: 'يبدأ الأسبوع يوم', overtimeAfter: 'العمل الإضافي بعد (ساعة أسبوعياً)', overtimeRate: 'معدل العمل الإضافي',
  approvalRules: 'قواعد الموافقة', approvalRulesBody: 'يوافق مدير على مصاريف الموظفين، وتحتاج المبالغ الأكبر موافقة المالك أيضاً.', ownerApprovalOver: 'موافقة المالك فوق',
  alertThresholds: 'التنبيهات الذكية', alertThresholdsBody: 'تصلك إشعارات عند تجاوز هذه الحدود.', alert_payroll: 'ارتفاع الرواتب', alert_category: 'ارتفاع إنفاق فئة',
  alert_revenue: 'انخفاض الإيرادات', alert_overtime: 'ارتفاع العمل الإضافي', alert_margin: 'هامش الربح أقل من', alert_large: 'مصروف كبير ابتداءً من',
  alertField_payrollIncreasePct: 'ارتفاع الرواتب', alertField_categoryIncreasePct: 'ارتفاع فئة', alertField_revenueDropPct: 'انخفاض الإيرادات',
  alertField_overtimeIncreasePct: 'ارتفاع العمل الإضافي', alertField_marginBelowPct: 'الهامش أقل من',
  authSettings: 'أمان تسجيل الدخول', authSettingsBody: 'للمالك فقط.', requirePhone: 'اشتراط رقم هاتف متحقق منه',
  departmentsBody: 'مدير القسم يرى قسمه فقط ويديره.', managedBy: 'يديره', noManager: 'بلا مدير',
  noDepartments: 'لا توجد أقسام بعد.', noLocations: 'لا توجد مواقع بعد.', expenseCategories: 'فئات المصاريف',
  expenseCategoriesBody: 'يمكن إعادة تسمية الفئات المدمجة أو إخفاؤها دون حذفها.', revenueCategories: 'فئات الإيرادات', moreSettings: 'المزيد',
  rolesPermissions: 'الأدوار والصلاحيات', importOldApp: 'الاستيراد من تطبيق المصاريف',
  importOldAppBody: 'في تطبيق المصاريف اختر فترة «هذه السنة» أو أطول واضغط «تصدير CSV»، ثم اختر ذلك الملف هنا. تُتجاوز المصاريف المرفوضة، واستيراد الملف نفسه مرة أخرى لا يكرر شيئاً.', chooseExportFile: 'اختر ملف التصدير',
  currencyHint: 'ثلاثة أحرف مثل IQD أو USD، وتُقفل بعد تسجيل أي مبالغ.', addDepartment: 'إضافة قسم', departmentManager: 'مدير القسم',
  departmentManagerHint: 'اتركه فارغاً ليرى كل المدراء هذا القسم.', addLocation: 'إضافة موقع', addCategory: 'إضافة فئة',
  nameAr: 'الاسم بالعربية', nameEn: 'الاسم بالإنجليزية', claimable: 'يمكن للموظفين المطالبة بها', claimableLong: 'يمكن للموظفين تقديم مصاريف عمل في هذه الفئة',
  importResult: 'استُورد {n} مصروفاً و{s} سجل رواتب، وتُجووز {skipped} مرفوضاً، و{again} كانت مستوردة سابقاً.',
  importDone: 'اكتمل الاستيراد', importBadFile: 'هذا الملف ليس ملف تصدير صالحاً.',
  kind_fixed: 'ثابتة', kind_operating: 'تشغيلية', kind_payroll: 'رواتب', kind_other: 'أخرى', kind_sale: 'مبيعات', kind_service: 'خدمات',
  kind_refund: 'مرتجعات', kind_adjustment: 'تسوية',
  sg_employees: 'الأشخاص', sg_departments: 'الأقسام', sg_shifts: 'المناوبات', sg_employeeExpenses: 'مصاريف الموظفين',
  sg_businessExpenses: 'مصاريف النشاط', sg_revenue: 'الإيرادات', sg_payroll: 'الرواتب', sg_reports: 'التقارير',
  'e.amount': 'أدخل مبلغاً أكبر من صفر.', 'e.invalid_category': 'اختر فئة.', 'e.invalid_receipt': 'ارفع الوصل مجدداً.',
  'e.future_date': 'لا يمكن أن يكون التاريخ في المستقبل.', 'e.locked': 'لم يعد بالإمكان تغيير هذا.', 'e.not_pending': 'تم البت في هذا مسبقاً.',
  'e.reason_required': 'اذكر السبب.', 'e.not_approved': 'يمكن تعويض المصاريف الموافق عليها فقط.', 'e.in_payroll': 'يُعوَّض هذا ضمن الرواتب.',
  'e.run_locked': 'هذه الرواتب مقفلة.', 'e.needs_review': 'أزل تأشير المراجعة أولاً.', 'e.period_overlap': 'هناك رواتب أخرى تغطي جزءاً من هذه الفترة.',
  'e.period_locked': 'هذا الوقت ضمن رواتب مدفوعة ولا يمكن تغييره.', 'e.already_clocked_in': 'سجّلت حضورك مسبقاً.',
  'e.not_clocked_in': 'لم تسجّل حضورك.', 'e.invalid_break': 'الاستراحة أطول من وقت العمل.', 'e.invalid_times': 'راجع الأوقات.',
  'e.shift_closed': 'لم يعد بالإمكان تغيير هذه المناوبة.', 'e.already_requested': 'هناك طلب معلّق لهذه المناوبة.',
  'e.shift_changed': 'تغيّرت المناوبة بعد تقديم الطلب.', 'e.no_taker': 'لم يأخذ أحد هذه المناوبة بعد.',
  'e.not_available': 'أُخذت هذه المناوبة مسبقاً.', 'e.invalid_taker': 'اختر زميلاً.', 'e.shift_required': 'اختر مناوبة.',
  'e.file_type': 'ارفع صورة (JPEG أو PNG أو WebP) أو ملف PDF.', 'e.file_too_large': 'الملف كبير جداً.', 'e.empty_file': 'الملف فارغ.',
  'e.confirm_mismatch': 'اكتب الاسم الكامل كما هو.', 'e.has_records': 'لهذا الشخص سجلات يجب الاحتفاظ بها، فأبقه مؤرشفاً.',
  'e.currency_locked': 'لا يمكن تغيير العملة بعد تسجيل أي مبالغ.', 'e.invalid_timezone': 'منطقة زمنية غير معروفة.',
  'e.duplicate_name': 'هذا الاسم مستخدم.', 'e.duplicate_budget': 'هناك ميزانية لهذا مسبقاً.', 'e.invalid_manager': 'اختر مديراً.',
  'e.invalid_department': 'اختر قسماً.', 'e.invalid_location': 'اختر موقعاً.', 'e.invalid_member': 'اختر شخصاً من فريقك.',
  'e.invalid_amount': 'راجع المبلغ.', 'e.range_too_long': 'اختر فترة أقصر.', 'e.invalid_range': 'يجب أن يكون تاريخ النهاية بعد البداية.',
  'e.archived': 'استعد هذا السجل أولاً.', 'e.interval_required': 'اختر عدد الأيام بين الدفعات.', 'e.invalid_budget': 'ميزانية الفئة تحتاج فئة.',
  'a.attendance.added': 'أضاف {actor} حضوراً لـ {target}', 'a.attendance.adjusted': 'صحّح {actor} حضور {target}',
  'a.attendance.clock_in': 'سجّل {actor} حضوره', 'a.attendance.clock_out': 'سجّل {actor} انصرافه',
  'a.auth.login': 'سجّل {actor} الدخول', 'a.auth.login_recovery_code': 'سجّل {actor} الدخول برمز استرداد', 'a.auth.logout_all': 'سجّل {actor} الخروج من كل الأجهزة',
  'a.auth.logout_other_devices': 'سجّل {actor} الخروج من الأجهزة الأخرى', 'a.auth.password_changed': 'غيّر {actor} كلمة المرور',
  'a.auth.password_reset': 'أعاد {actor} تعيين كلمة المرور', 'a.auth.password_reset_requested': 'طُلبت إعادة تعيين كلمة المرور لـ {actor}',
  'a.auth.email_verified': 'تحقق {actor} من بريده', 'a.auth.phone_verified': 'تحقق {actor} من هاتفه',
  'a.budget.created': 'أضاف {actor} ميزانية', 'a.budget.updated': 'عدّل {actor} ميزانية', 'a.business.settings_updated': 'غيّر {actor} إعدادات النشاط',
  'a.business_expense.created': 'سجّل {actor} مصروفاً للنشاط', 'a.business_expense.updated': 'عدّل {actor} مصروفاً للنشاط',
  'a.business_expense.archived': 'أرشف {actor} مصروفاً للنشاط', 'a.business_expense.restored': 'استعاد {actor} مصروفاً للنشاط',
  'a.category.created': 'أضاف {actor} فئة', 'a.category.updated': 'عدّل {actor} فئة',
  'a.department.created': 'أضاف {actor} قسماً', 'a.department.updated': 'عدّل {actor} قسماً',
  'a.location.created': 'أضاف {actor} موقعاً', 'a.location.updated': 'عدّل {actor} موقعاً',
  'a.document.uploaded': 'رفع {actor} مستنداً', 'a.document.archived': 'أرشف {actor} مستنداً',
  'a.employee_expense.created': 'قدّم {actor} مصروفاً', 'a.employee_expense.review': 'وضع {actor} مصروفاً قيد المراجعة',
  'a.employee_expense.approved': 'وافق {actor} على مصروف', 'a.employee_expense.approved_step1': 'وافق {actor} على مصروف وأحاله للمالك',
  'a.employee_expense.reject': 'رفض {actor} مصروفاً', 'a.employee_expense.reimbursed': 'أشّر {actor} مصروفاً كمعوَّض',
  'a.import.expenses_app': 'استورد {actor} سجلات من تطبيق المصاريف',
  'a.member.archived': 'أرشف {actor} {target}', 'a.member.deleted': 'حذف {actor} شخصاً نهائياً', 'a.member.pay_changed': 'غيّر {actor} أجر {target}',
  'a.member.profile_updated': 'حدّث {actor} ملف {target}', 'a.member.reinstated': 'أعاد {actor} تعيين {target}', 'a.member.terminated': 'أنهى {actor} خدمة {target}',
  'a.payroll.run_created': 'بدأ {actor} الرواتب', 'a.payroll.recalculated': 'أعاد {actor} حساب الرواتب', 'a.payroll.finalized': 'اعتمد {actor} الرواتب',
  'a.payroll.reopened': 'أعاد {actor} فتح الرواتب', 'a.payroll.paid': 'أشّر {actor} الرواتب كمدفوعة', 'a.payroll.flagged_for_review': 'أشّر {actor} راتباً للمراجعة',
  'a.payroll.review_cleared': 'أزال {actor} تأشير مراجعة راتب', 'a.payroll.item_removed': 'حذف {actor} بنداً من الرواتب', 'a.payroll.bonus_added': 'أضاف {actor} مكافأة',
  'a.payroll.deduction_added': 'أضاف {actor} استقطاعاً', 'a.payroll.adjustment_added': 'أضاف {actor} تسوية على الراتب',
  'a.recurring_expense.created': 'أضاف {actor} مصروفاً متكرراً', 'a.recurring_expense.updated': 'عدّل {actor} مصروفاً متكرراً',
  'a.report.exported': 'صدّر {actor} تقريراً', 'a.revenue.created': 'سجّل {actor} إيراداً', 'a.revenue.updated': 'عدّل {actor} إيراداً',
  'a.revenue.archived': 'أرشف {actor} إيراداً', 'a.revenue.restored': 'استعاد {actor} إيراداً', 'a.schedule.published': 'نشر {actor} الجدول',
  'a.shift.created': 'أضاف {actor} مناوبة', 'a.shift.updated': 'عدّل {actor} مناوبة', 'a.shift.cancelled': 'ألغى {actor} مناوبة',
  'a.shift.assigned': 'أسند {actor} مناوبة', 'a.shift.changed': 'غيّر {actor} مناوبة',
  'a.shift_request.created': 'طلب {actor} تغيير مناوبة', 'a.shift_request.approved': 'وافق {actor} على طلب مناوبة',
  'a.shift_request.rejected': 'رفض {actor} طلب مناوبة', 'a.shift_request.cancelled': 'ألغى {actor} طلب مناوبة',
  'a.swap.requested': 'طلب {actor} تبديلاً', 'a.swap.accepted_by_colleague': 'قبل {actor} تبديلاً', 'a.swap.declined_by_colleague': 'رفض {actor} تبديلاً',
  'a.swap.approved': 'وافق {actor} على تبديل', 'a.swap.rejected': 'رفض {actor} تبديلاً', 'a.swap.cancelled': 'ألغى {actor} تبديلاً',
  'a.time_off.approved': 'وافق {actor} على إجازة', 'a.time_off.rejected': 'رفض {actor} إجازة',
  filter_shift: 'المناوبات', filter_swap: 'التبديلات', filter_payroll: 'الرواتب', filter_employee_expense: 'مصاريف الموظفين',
  filter_business_expense: 'مصاريف النشاط', filter_revenue: 'الإيرادات', filter_attendance: 'الحضور', filter_auth: 'تسجيلات الدخول',
  'e.invalid_shift': 'اختر مناوبة صالحة.', 'e.invalid_document': 'ارفع الملف مجدداً.', 'e.no_contact': 'لا يملك هذا الشخص بريداً أو هاتفاً متحققاً منه.',
  'e.import_bad_file': 'هذا الملف ليس ملف تصدير من تطبيق المصاريف.', 'e.invalid_value': 'راجع القيمة.', 'e.range_required': 'اختر فترة.', 'e.unknown_permission': 'صلاحية غير معروفة.',
  'n.invitation.accepted': 'قبل {name} دعوتك', 'n.role.changed': 'تغيّر دورك', 'n.member.suspended': 'أُوقف وصولك',
  'n.member.active': 'أُعيد وصولك', 'n.shift.assigned': 'لديك مناوبة جديدة', 'n.shift.changed': 'تغيّرت إحدى مناوباتك',
  'n.shift.cancelled': 'أُلغيت إحدى مناوباتك', 'n.schedule.published': 'جدولك الجديد جاهز ({count} مناوبات)',
  'n.shift.offered': 'عرض عليك زميل مناوبة', 'n.shift.offer_taken': 'عرض أحدهم أخذ مناوبتك',
  'n.request.new': 'طلب مناوبة بانتظار مراجعتك', 'n.request.approved': 'تمت الموافقة على طلب المناوبة', 'n.request.rejected': 'رُفض طلب المناوبة',
  'n.time_off.approved': 'تمت الموافقة على إجازتك', 'n.time_off.rejected': 'رُفض طلب إجازتك',
  'n.swap.requested': 'يريد زميل تبديل مناوبة معك', 'n.swap.accepted': 'قُبل التبديل وهو بانتظار الموافقة',
  'n.swap.awaiting_approval': 'تبديل مناوبة بانتظار موافقتك', 'n.swap.approved': 'تمت الموافقة على تبديل المناوبة', 'n.swap.rejected': 'رُفض تبديل المناوبة',
  'n.swap.cancelled': 'أُلغي تبديل مناوبة', 'n.expense.submitted': 'مصروف بقيمة {amount} بانتظار المراجعة',
  'n.expense.owner_approval': 'مصروف بقيمة {amount} بانتظار موافقتك', 'n.expense.approved': 'تمت الموافقة على مصروفك بقيمة {amount}',
  'n.expense.rejected': 'رُفض مصروفك: {reason}', 'n.expense.reimbursed': 'عُوّض مصروفك بقيمة {amount}',
  'n.finance.large_expense': 'سُجّل مصروف كبير بقيمة {amount}', 'n.salary.pending': 'راتب هذه الفترة جاهز: {net}',
  'n.salary.paid': 'دُفع لك {net}',
  'n.alert.payroll_increase': 'ارتفعت الرواتب {pct}٪ عن الشهر الماضي', 'n.alert.revenue_drop': 'انخفضت الإيرادات {pct}٪ عن الشهر الماضي',
  'n.alert.category_increase': 'ارتفع إنفاق {nameAr} بنسبة {pct}٪', 'n.alert.overtime_increase': 'ارتفع العمل الإضافي {pct}٪',
  'n.alert.margin_low': 'انخفض هامش الربح إلى {margin}٪ (حدّك {threshold}٪)', 'n.alert.budget_over': 'تجاوزت ميزانية {categoryAr} حدها',
  'n.alert.budget_near': 'استُخدم {used}٪ من ميزانية {categoryAr}',
};
